// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwzwjfrntxqhmrvoriuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3endqZnJudHhxaG1ydm9yaXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzg1OTQsImV4cCI6MjA2ODkxNDU5NH0.E87G-NR8hD9HQSXxOqI_k4nWHeCAnPAUCL5i025jrLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});